/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import PrincipalEjecuccion.*;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonnathan Campoberde
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private static String campoOrdenamiento;
    private static String ruta;
    private static String algoritmo;
    private static boolean obtencionCorrecta;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRutaDelArchivo = new javax.swing.JLabel();
        jButtonSalirAplicacion = new javax.swing.JButton();
        jButtonRealizarOrdenamiento = new javax.swing.JButton();
        jLabelCampoAOrdenar = new javax.swing.JLabel();
        jTextFieldRutaDelArchivo = new javax.swing.JTextField();
        jComboBoxCampoOrdenamiento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxAlgoritmo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombreArchivo = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ordenamientos Externos");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRutaDelArchivo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelRutaDelArchivo.setText("Ruta absoluta de la carpeta del archivo: ");
        getContentPane().add(jLabelRutaDelArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 50));

        jButtonSalirAplicacion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonSalirAplicacion.setText("Salir");
        jButtonSalirAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirAplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalirAplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 120, 30));

        jButtonRealizarOrdenamiento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonRealizarOrdenamiento.setText("Ordenar");
        jButtonRealizarOrdenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarOrdenamientoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRealizarOrdenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 180, 30));

        jLabelCampoAOrdenar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelCampoAOrdenar.setText("Campo de ordenamiento");
        getContentPane().add(jLabelCampoAOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jTextFieldRutaDelArchivo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldRutaDelArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 310, 30));

        jComboBoxCampoOrdenamiento.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxCampoOrdenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "String", "Enteros", "Booleano", "Fecha" }));
        jComboBoxCampoOrdenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCampoOrdenamientoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCampoOrdenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 220, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Algoritmo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 240, 30));

        jComboBoxAlgoritmo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intercalación Directa", "Intercalación Natural", "Intercalacion Polifasica", "" }));
        jComboBoxAlgoritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlgoritmoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxAlgoritmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 340, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nombre del archivo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jTextFieldNombreArchivo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldNombreArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 108, 340, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabelFondo.setName("fondo"); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirAplicacionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirAplicacionActionPerformed

    private void jButtonRealizarOrdenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarOrdenamientoActionPerformed

        ruta = jTextFieldRutaDelArchivo.getText()+"\\";
        ruta=ruta+jTextFieldNombreArchivo.getText()+".csv";
        campoOrdenamiento = jComboBoxCampoOrdenamiento.getSelectedItem().toString();
        algoritmo = jComboBoxAlgoritmo.getSelectedItem().toString();

        Principal.ejecuccionOrdenamientosAlgoritmo();


    }//GEN-LAST:event_jButtonRealizarOrdenamientoActionPerformed

    private void jComboBoxCampoOrdenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCampoOrdenamientoActionPerformed
        campoOrdenamiento = jComboBoxCampoOrdenamiento.getSelectedItem().toString();

    }//GEN-LAST:event_jComboBoxCampoOrdenamientoActionPerformed

    private void jComboBoxAlgoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlgoritmoActionPerformed
        algoritmo = jComboBoxAlgoritmo.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxAlgoritmoActionPerformed

    private void jTextFieldNombreArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreArchivoActionPerformed

    public static String getCampoOrdenar() {
        return campoOrdenamiento;
    }

    public static String getAlgortimo() {
        return algoritmo;
    }

    public static String getRuta() {
        return ruta;
    }

    /**
     * @param args the command line arguments
     */

    public static void ejecutar() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRealizarOrdenamiento;
    private javax.swing.JButton jButtonSalirAplicacion;
    private javax.swing.JComboBox<String> jComboBoxAlgoritmo;
    public static javax.swing.JComboBox<String> jComboBoxCampoOrdenamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCampoAOrdenar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelRutaDelArchivo;
    private javax.swing.JTextField jTextFieldNombreArchivo;
    private javax.swing.JTextField jTextFieldRutaDelArchivo;
    // End of variables declaration//GEN-END:variables
}
