/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import PrincipalEjecuccion.*;
import com.csvreader.CsvReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jonnathan Campoberde
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private static String campoOrdenamiento;
    private static String ruta=null;
    private static String algoritmo;
    private static boolean obtencionCorrecta;
    private static int vecesOrdenar = 1;
    private static boolean ejecutar = true;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalirAplicacion = new javax.swing.JButton();
        jButtonRealizarOrdenamiento = new javax.swing.JButton();
        jLabelCampoAOrdenar = new javax.swing.JLabel();
        jComboBoxCampoOrdenamiento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxAlgoritmo = new javax.swing.JComboBox<>();
        jButtonBotonBuscarRuta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldVecesEjecutar = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ordenamientos Externos");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalirAplicacion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonSalirAplicacion.setText("Salir");
        jButtonSalirAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirAplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalirAplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 120, 30));

        jButtonRealizarOrdenamiento.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonRealizarOrdenamiento.setText("Ordenar");
        jButtonRealizarOrdenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarOrdenamientoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRealizarOrdenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 180, 30));

        jLabelCampoAOrdenar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelCampoAOrdenar.setText("Campo de ordenamiento");
        getContentPane().add(jLabelCampoAOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jComboBoxCampoOrdenamiento.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxCampoOrdenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "String", "Enteros", "Booleano", "Fecha" }));
        jComboBoxCampoOrdenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCampoOrdenamientoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCampoOrdenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 220, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Algoritmo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 240, 30));

        jComboBoxAlgoritmo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBoxAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intercalación Directa", "Intercalación Natural" }));
        jComboBoxAlgoritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlgoritmoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxAlgoritmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 340, -1));

        jButtonBotonBuscarRuta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonBotonBuscarRuta.setText("Buscar Archivo");
        jButtonBotonBuscarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBotonBuscarRutaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBotonBuscarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 130, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Veces a ejecutar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jTextFieldVecesEjecutar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldVecesEjecutar.setText("1");
        jTextFieldVecesEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVecesEjecutarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldVecesEjecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 140, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabelFondo.setName("fondo"); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirAplicacionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirAplicacionActionPerformed

    private void jButtonRealizarOrdenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarOrdenamientoActionPerformed

        //deno de cambiar y devolver la ruta ruta = jTextFieldRutaDelArchivo.getText()+"\\";
        //ruta=ruta+jTextFieldNombreArchivo.getText()+".csv";
        campoOrdenamiento = jComboBoxCampoOrdenamiento.getSelectedItem().toString();
        algoritmo = jComboBoxAlgoritmo.getSelectedItem().toString();
        try {
            vecesOrdenar = Integer.parseInt(jTextFieldVecesEjecutar.getText());
        } catch (NumberFormatException ex) {
            ejecutar = false;
            JOptionPane.showMessageDialog(null, "No es un tipo de dato numerico", "Error en el campo veces a ejecutar", JOptionPane.ERROR_MESSAGE);
        }
        if (ejecutar&&(vecesOrdenar>0)) {
            Principal.ejecuccionOrdenamientosAlgoritmo();
        }else{
            JOptionPane.showMessageDialog(null,"No se puede ejecutar la informacion ingresada es incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonRealizarOrdenamientoActionPerformed

    private void jComboBoxCampoOrdenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCampoOrdenamientoActionPerformed
        campoOrdenamiento = jComboBoxCampoOrdenamiento.getSelectedItem().toString();

    }//GEN-LAST:event_jComboBoxCampoOrdenamientoActionPerformed

    private void jComboBoxAlgoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlgoritmoActionPerformed
        algoritmo = jComboBoxAlgoritmo.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBoxAlgoritmoActionPerformed

    private void jButtonBotonBuscarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBotonBuscarRutaActionPerformed
        JFileChooser ventanaBusqueda = new JFileChooser();//Objeto ventana de busqueda
        ventanaBusqueda.setFileSelectionMode(JFileChooser.FILES_ONLY);//Tipo de busqueda
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".CSV", "CSV");
        ventanaBusqueda.setFileFilter(filter);//Extenciones
        //ventanaBusqueda.setMultiSelectionEnabled(true);//Seleccionar varios archivos
        int returnVal = ventanaBusqueda.showOpenDialog(null);//Condicional de aceptacion seleccion
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File archivo = ventanaBusqueda.getSelectedFile();
            ruta = archivo.getAbsolutePath();
        }
    }//GEN-LAST:event_jButtonBotonBuscarRutaActionPerformed

    private void jTextFieldVecesEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVecesEjecutarActionPerformed
       
    }//GEN-LAST:event_jTextFieldVecesEjecutarActionPerformed

    public static String getCampoOrdenar() {
        return campoOrdenamiento;
    }

    public static String getAlgortimo() {
        return algoritmo;
    }

    public static String getRuta() {
        return ruta;
    }

    public static int getVecesEjecutar() {
        return vecesOrdenar;
    }

    /**
     * @param args the command line arguments
     */

    public static void ejecutar() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBotonBuscarRuta;
    private javax.swing.JButton jButtonRealizarOrdenamiento;
    private javax.swing.JButton jButtonSalirAplicacion;
    private javax.swing.JComboBox<String> jComboBoxAlgoritmo;
    public static javax.swing.JComboBox<String> jComboBoxCampoOrdenamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCampoAOrdenar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField jTextFieldVecesEjecutar;
    // End of variables declaration//GEN-END:variables
}
